# Generated by Django 4.2.6 on 2023-10-22 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0002_userstocks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStocks',
            new_name='UserStock',
        ),
        migrations.AlterModelOptions(
            name='userstock',
            options={'verbose_name': 'hello'},
        ),
    ]
