# Generated by Django 4.2.6 on 2023-10-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0003_rename_userstocks_userstock_alter_userstock_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstock',
            options={},
        ),
        migrations.RenameField(
            model_name='userstock',
            old_name='stock_id',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='userstock',
            old_name='user_id',
            new_name='user',
        ),
    ]
